@echo off
echo Starting LiveSysDesign locally...

echo Step 1: Starting Docker containers...
docker-compose up -d

echo Waiting 30 seconds for containers...
timeout /t 30

echo Step 2: Starting Gateway...
start cmd /k "cd gateway && npm run dev"

echo Step 3: Starting Sim Engine...
start cmd /k "cd sim-engine && go run cmd/server/main.go"

echo Step 4: Starting Frontend...
start cmd /k "cd frontend && npm run dev"

echo Step 5: Starting AI Engine...
start cmd /k "cd ai-engine && .\venv\Scripts\Activate.ps1 && uvicorn main:app --port 6000 --reload"

echo All services starting...
echo Open http://localhost:3000 in 60 seconds
pause