// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	DesignId     string                 `protobuf:"bytes,2,opt,name=design_id,json=designId,proto3" json:"design_id,omitempty"`
	// JSON stringified graph data from the frontend
	GraphJson     string `protobuf:"bytes,3,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *StartRequest) GetDesignId() string {
	if x != nil {
		return x.DesignId
	}
	return ""
}

func (x *StartRequest) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InjectFailureRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	NodeId       string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Options: "KILL", "SLOW", "DROP", "PARTITION"
	FailureType   string `protobuf:"bytes,3,opt,name=failure_type,json=failureType,proto3" json:"failure_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFailureRequest) Reset() {
	*x = InjectFailureRequest{}
	mi := &file_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFailureRequest) ProtoMessage() {}

func (x *InjectFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFailureRequest.ProtoReflect.Descriptor instead.
func (*InjectFailureRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *InjectFailureRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *InjectFailureRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InjectFailureRequest) GetFailureType() string {
	if x != nil {
		return x.FailureType
	}
	return ""
}

type InjectFailureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFailureResponse) Reset() {
	*x = InjectFailureResponse{}
	mi := &file_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFailureResponse) ProtoMessage() {}

func (x *InjectFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFailureResponse.ProtoReflect.Descriptor instead.
func (*InjectFailureResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *InjectFailureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InjectFailureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFailureRequest) Reset() {
	*x = RemoveFailureRequest{}
	mi := &file_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFailureRequest) ProtoMessage() {}

func (x *RemoveFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFailureRequest.ProtoReflect.Descriptor instead.
func (*RemoveFailureRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveFailureRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *RemoveFailureRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveFailureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFailureResponse) Reset() {
	*x = RemoveFailureResponse{}
	mi := &file_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFailureResponse) ProtoMessage() {}

func (x *RemoveFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFailureResponse.ProtoReflect.Descriptor instead.
func (*RemoveFailureResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveFailureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFailureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_simulation_proto protoreflect.FileDescriptor

const file_simulation_proto_rawDesc = "" +
	"\n" +
	"\x10simulation.proto\x12\n" +
	"simulation\"o\n" +
	"\fStartRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x1b\n" +
	"\tdesign_id\x18\x02 \x01(\tR\bdesignId\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x03 \x01(\tR\tgraphJson\"C\n" +
	"\rStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\vStopRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x14InjectFailureRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\ffailure_type\x18\x03 \x01(\tR\vfailureType\"K\n" +
	"\x15InjectFailureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x14RemoveFailureRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"K\n" +
	"\x15RemoveFailureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcc\x02\n" +
	"\x11SimulationService\x12F\n" +
	"\x0fStartSimulation\x12\x18.simulation.StartRequest\x1a\x19.simulation.StartResponse\x12C\n" +
	"\x0eStopSimulation\x12\x17.simulation.StopRequest\x1a\x18.simulation.StopResponse\x12T\n" +
	"\rInjectFailure\x12 .simulation.InjectFailureRequest\x1a!.simulation.InjectFailureResponse\x12T\n" +
	"\rRemoveFailure\x12 .simulation.RemoveFailureRequest\x1a!.simulation.RemoveFailureResponseB$Z\"livesysdesign/sim-engine/api/protob\x06proto3"

var (
	file_simulation_proto_rawDescOnce sync.Once
	file_simulation_proto_rawDescData []byte
)

func file_simulation_proto_rawDescGZIP() []byte {
	file_simulation_proto_rawDescOnce.Do(func() {
		file_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)))
	})
	return file_simulation_proto_rawDescData
}

var file_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_simulation_proto_goTypes = []any{
	(*StartRequest)(nil),          // 0: simulation.StartRequest
	(*StartResponse)(nil),         // 1: simulation.StartResponse
	(*StopRequest)(nil),           // 2: simulation.StopRequest
	(*StopResponse)(nil),          // 3: simulation.StopResponse
	(*InjectFailureRequest)(nil),  // 4: simulation.InjectFailureRequest
	(*InjectFailureResponse)(nil), // 5: simulation.InjectFailureResponse
	(*RemoveFailureRequest)(nil),  // 6: simulation.RemoveFailureRequest
	(*RemoveFailureResponse)(nil), // 7: simulation.RemoveFailureResponse
}
var file_simulation_proto_depIdxs = []int32{
	0, // 0: simulation.SimulationService.StartSimulation:input_type -> simulation.StartRequest
	2, // 1: simulation.SimulationService.StopSimulation:input_type -> simulation.StopRequest
	4, // 2: simulation.SimulationService.InjectFailure:input_type -> simulation.InjectFailureRequest
	6, // 3: simulation.SimulationService.RemoveFailure:input_type -> simulation.RemoveFailureRequest
	1, // 4: simulation.SimulationService.StartSimulation:output_type -> simulation.StartResponse
	3, // 5: simulation.SimulationService.StopSimulation:output_type -> simulation.StopResponse
	5, // 6: simulation.SimulationService.InjectFailure:output_type -> simulation.InjectFailureResponse
	7, // 7: simulation.SimulationService.RemoveFailure:output_type -> simulation.RemoveFailureResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simulation_proto_init() }
func file_simulation_proto_init() {
	if File_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulation_proto_goTypes,
		DependencyIndexes: file_simulation_proto_depIdxs,
		MessageInfos:      file_simulation_proto_msgTypes,
	}.Build()
	File_simulation_proto = out.File
	file_simulation_proto_goTypes = nil
	file_simulation_proto_depIdxs = nil
}
